{% set version = "0.1.5" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: python-consul2
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python-consul2/python-consul2-{{ version }}.tar.gz
  sha256: 29c859de73e17f36ab99be831fdc1d924f16e8772233277a28ef92b7b99995cd

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - six >=1.4

test:
  imports:
    - consul
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: python-consul2

  - name: python-consul2-with-tornado
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("python-consul2", max_pin="x.x.x") }}
        - tornado
    test:
      imports:
        - consul.tornado
      commands:
        - pip check
      requires:
        - pip

  - name: python-consul2-with-aiohttp
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("python-consul2", max_pin="x.x.x") }}
        - aiohttp
    test:
      imports:
        - consul.aio
      commands:
        - pip check
      requires:
        - pip

  - name: python-consul2-with-twisted
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("python-consul2", max_pin="x.x.x") }}
        - treq
        - twisted
    test:
      imports:
        - consul.twisted
      commands:
        - pip check
      requires:
        - pip

  - name: python-consul2-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("python-consul2-with-aiohttp", max_pin="x.x.x") }}
        - {{ pin_subpackage("python-consul2-with-tornado", max_pin="x.x.x") }}
        - {{ pin_subpackage("python-consul2-with-twisted", max_pin="x.x.x") }}
        - {{ pin_subpackage("python-consul2", max_pin="x.x.x") }}
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - consul
        - consul.twisted
        - consul.tornado
        - consul.aio
      commands:
        - pip check

about:
  home: https://github.com/poppyred/python-consul2
  summary: Python client for Consul (http://www.consul.io/)
  license: MIT
  license_file: LICENSE

extra:
  feedstock-name: python-consul2-split
  recipe-maintainers:
    - bollwyvl
