{% set version = "0.1.5" %}

package:
  name: python-consul2-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-consul2/python-consul2-{{ version }}.tar.gz
  sha256: 29c859de73e17f36ab99be831fdc1d924f16e8772233277a28ef92b7b99995cd

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
  run:
    - python >=3.6

outputs:
  - name: python-consul2
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - requests
        - six >=1.4
    test:
      imports:
        - consul
      commands:
        - pip check
      requires:
        - pip

  - name: python-consul2-with-tornado
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("python-consul2", max_pin="x.x.x") }}
        - python >=3.6
        - tornado
    test:
      imports:
        - consul.tornado
      commands:
        - pip check
      requires:
        - pip

  - name: python-consul2-with-aiohttp
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("python-consul2", max_pin="x.x.x") }}
        - aiohttp
        - python >=3.6
    test:
      imports:
        - consul.aio
      commands:
        - pip check
      requires:
        - pip

  - name: python-consul2-with-twisted
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("python-consul2", max_pin="x.x.x") }}
        - python >=3.6
        - treq
        - twisted
    test:
      imports:
        - consul.twisted
      commands:
        - pip check
      requires:
        - pip

  - name: python-consul2-with-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("python-consul2-with-aiohttp", max_pin="x.x.x") }}
        - {{ pin_subpackage("python-consul2-with-tornado", max_pin="x.x.x") }}
        - {{ pin_subpackage("python-consul2-with-twisted", max_pin="x.x.x") }}
        - {{ pin_subpackage("python-consul2", max_pin="x.x.x") }}
        - python >=3.6
    test:
      imports:
        - consul
        - consul.twisted
        - consul.tornado
        - consul.aio
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/poppyred/python-consul2
  summary: Python client for Consul (http://www.consul.io/)
  license: MIT
  license_file: LICENSE

extra:
  feedstock-name: python-consul2-split
  recipe-maintainers:
    - bollwyvl
